// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_manage_system_backend.Shares;

namespace project_manage_system_backend.Migrations
{
    [DbContext(typeof(PMSContext))]
    [Migration("20201115141216_ProjAndRepo")]
    partial class ProjAndRepo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("project_manage_system_backend.Models.ProjectModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.RepositoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authority")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectModelID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProjectModelID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.ProjectModel", b =>
                {
                    b.HasOne("project_manage_system_backend.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.RepositoryModel", b =>
                {
                    b.HasOne("project_manage_system_backend.Models.UserModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID");

                    b.HasOne("project_manage_system_backend.Models.ProjectModel", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.UserModel", b =>
                {
                    b.HasOne("project_manage_system_backend.Models.ProjectModel", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectModelID");
                });

            modelBuilder.Entity("project_manage_system_backend.Models.ProjectModel", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
